objectifs:
  - DRI . cotisations

questions:
  liste noire:
    - dirigeant . indépendant . cotisations facultatives
    - entreprise . effectif . seuil
    - entreprise . imposition . IR . micro-fiscal
  liste:
    - DRI . cotisations
    - ''

unité par défaut: '€'

situation:
  DRI: oui
