objectifs:
  - DRI . cotisations

questions:
  liste noire:
    - dirigeant . indépendant . cotisations facultatives
    - entreprise . salariés . effectif . seuil
    - entreprise . imposition . régime . micro-entreprise
  liste:
    - DRI . cotisations
    - ''

unité par défaut: '€'

situation:
  DRI: oui
  impôt:
    non applicable si: oui
