rules:
  quotes:
    - 1 # While https://github.com/eslint/eslint/issues/9662#issuecomment-353958854 we don't enforce this
    - single
    - avoidEscape: true
  no-console: 1
  no-restricted-globals: [2, 'length']
  no-global-assign: 0
  no-unsafe-negation: 0
  react/prop-types: 0
  react/jsx-no-target-blank: 0
  react/no-unescaped-entities: 0
  react/display-name: 1
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
parser: babel-eslint

plugins:
  - react
  - react-hooks
  - flowtype
env:
  browser: true
  commonjs: true
  es6: true
settings:
  react:
    version: 'detect'
    flowVersion: '0.92'

overrides:
  files: ['*.test.js', 'cypress/integration/**/*.js']
  env:
    mocha: true

globals:
  process: false

extends:
  - eslint:recommended
  - plugin:flowtype/recommended
  - plugin:react/recommended
  - prettier
  - prettier/flowtype
  - prettier/react
parserOptions:
  ecmaFeatures:
    jsx: true
