enableMessageNames: false

enableScripts: false

nodeLinker: node-modules

# Protection supply chain : bloque les packages publiés récemment.
# Valeur temporairement élevée (6 mois) suite à l'attaque Shai Hulud 2.0 (24 nov. 2025).
# À réduire à 30 jours une fois la situation stabilisée.
npmMinimalAgeGate: 180d

yarnPath: .yarn/releases/yarn-4.12.0.cjs
