période:

période . jours ouvrés moyen par mois:
  formule: 21 jour ouvré/mois
  note: On retient 21 comme nombre de jours ouvrés moyen par mois

période . semaines par mois:
  unité: semaines/mois
  formule: 52 semaines/an / 12 mois/an

période . début d'année:
  formule: 01/01/2020

période . fin d'année:
  formule: 31/12/2020

plafond sécurité sociale temps plein:
  description: Le plafond de Sécurité sociale est le montant maximum des rémunérations à prendre en compte pour le calcul de certaines cotisations.
  acronyme: PSS
  formule: 3428 €/mois
  références:
    Urssaf.fr: https://www.urssaf.fr/portail/home/actualites/toute-lactualite-independant/plafond-de-la-securite-sociale-.html
    arrêté 2020: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000039440180

plafond horaire sécurité sociale:
  acronyme: PHSS
  formule: plafond sécurité sociale temps plein / 132 heures/mois
  unité: €/heure

plafond journalier sécurité sociale:
  acronyme: PJSS
  formule: plafond sécurité sociale temps plein / 18.15 jours/mois
  unité: €/jour

SMIC horaire:
  formule: 10.15 €/heure
  références:
    décret: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000037833206
    service-public.fr: https://www.service-public.fr/particuliers/vosdroits/F2300

SMIC temps plein:
  unité: €/mois

  formule:
    produit:
      assiette: contrat salarié . temps de travail . base légale * période . semaines par mois
      facteur: SMIC horaire
  références:
    décret: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000037833206

SMIC temps plein . net imposable:
  titre: SMIC net imposable
  description: Montant du SMIC net imposable pour un temps plein.
  formule:
    recalcul:
      règle: contrat salarié . rémunération . net imposable . base
      avec:
        contrat salarié . rémunération . brut de base: SMIC temps plein
  références:
    barème PAS: https://bofip.impots.gouv.fr/bofip/11255-PGP.html
