// flow-typed signature: 4b75985de26c8b5e1187a2d66f395f7d
// flow-typed version: <<STUB>>/akh_v^3.1.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'akh'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'akh' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'akh/tests/cont' {
  declare module.exports: any;
}

declare module 'akh/tests/maybe' {
  declare module.exports: any;
}

declare module 'akh/tests/reader' {
  declare module.exports: any;
}

declare module 'akh/tests/state' {
  declare module.exports: any;
}

declare module 'akh/tests/writer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'akh/index' {
  declare module.exports: $Exports<'akh'>;
}
declare module 'akh/index.js' {
  declare module.exports: $Exports<'akh'>;
}
declare module 'akh/tests/cont.js' {
  declare module.exports: $Exports<'akh/tests/cont'>;
}
declare module 'akh/tests/maybe.js' {
  declare module.exports: $Exports<'akh/tests/maybe'>;
}
declare module 'akh/tests/reader.js' {
  declare module.exports: $Exports<'akh/tests/reader'>;
}
declare module 'akh/tests/state.js' {
  declare module.exports: $Exports<'akh/tests/state'>;
}
declare module 'akh/tests/writer.js' {
  declare module.exports: $Exports<'akh/tests/writer'>;
}
