// flow-typed signature: 800e5774231f2cf8bd23645a546769f8
// flow-typed version: <<STUB>>/babel-plugin-webpack-alias_v^2.1.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-webpack-alias'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-webpack-alias' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-webpack-alias/build/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-webpack-alias/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'babel-plugin-webpack-alias/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'babel-plugin-webpack-alias/examples/ava/add10' {
  declare module.exports: any;
}

declare module 'babel-plugin-webpack-alias/examples/ava/deep/folder/alias/sum' {
  declare module.exports: any;
}

declare module 'babel-plugin-webpack-alias/examples/ava/webpack.config' {
  declare module.exports: any;
}

declare module 'babel-plugin-webpack-alias/examples/mocha/add10' {
  declare module.exports: any;
}

declare module 'babel-plugin-webpack-alias/examples/mocha/deep/folder/alias/sum' {
  declare module.exports: any;
}

declare module 'babel-plugin-webpack-alias/examples/mocha/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-webpack-alias/build/index.js' {
  declare module.exports: $Exports<'babel-plugin-webpack-alias/build/index'>;
}
declare module 'babel-plugin-webpack-alias/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'babel-plugin-webpack-alias/coverage/lcov-report/prettify'>;
}
declare module 'babel-plugin-webpack-alias/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'babel-plugin-webpack-alias/coverage/lcov-report/sorter'>;
}
declare module 'babel-plugin-webpack-alias/examples/ava/add10.js' {
  declare module.exports: $Exports<'babel-plugin-webpack-alias/examples/ava/add10'>;
}
declare module 'babel-plugin-webpack-alias/examples/ava/deep/folder/alias/sum.js' {
  declare module.exports: $Exports<'babel-plugin-webpack-alias/examples/ava/deep/folder/alias/sum'>;
}
declare module 'babel-plugin-webpack-alias/examples/ava/webpack.config.js' {
  declare module.exports: $Exports<'babel-plugin-webpack-alias/examples/ava/webpack.config'>;
}
declare module 'babel-plugin-webpack-alias/examples/mocha/add10.js' {
  declare module.exports: $Exports<'babel-plugin-webpack-alias/examples/mocha/add10'>;
}
declare module 'babel-plugin-webpack-alias/examples/mocha/deep/folder/alias/sum.js' {
  declare module.exports: $Exports<'babel-plugin-webpack-alias/examples/mocha/deep/folder/alias/sum'>;
}
declare module 'babel-plugin-webpack-alias/examples/mocha/webpack.config.js' {
  declare module.exports: $Exports<'babel-plugin-webpack-alias/examples/mocha/webpack.config'>;
}
