// flow-typed signature: f2b8570cf6bfaec77760ca12a7c75b49
// flow-typed version: <<STUB>>/fantasy-combinators_v0.0.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fantasy-combinators'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fantasy-combinators' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fantasy-combinators/combinators' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fantasy-combinators/combinators.js' {
  declare module.exports: $Exports<'fantasy-combinators/combinators'>;
}
