// flow-typed signature: 0c8c8afc0d3a6ae78020f5e7d82f2778
// flow-typed version: <<STUB>>/fantasy-land_v^3.5.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fantasy-land'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fantasy-land' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fantasy-land/internal/compose' {
  declare module.exports: any;
}

declare module 'fantasy-land/internal/func' {
  declare module.exports: any;
}

declare module 'fantasy-land/internal/id' {
  declare module.exports: any;
}

declare module 'fantasy-land/internal/index' {
  declare module.exports: any;
}

declare module 'fantasy-land/internal/patch' {
  declare module.exports: any;
}

declare module 'fantasy-land/internal/sum' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/alt' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/alternative' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/applicative' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/apply' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/bifunctor' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/category' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/chain' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/chainrec' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/comonad' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/contravariant' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/extend' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/filterable' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/foldable' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/functor' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/group' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/monad' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/monoid' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/ord' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/plus' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/profunctor' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/semigroup' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/semigroupoid' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/setoid' {
  declare module.exports: any;
}

declare module 'fantasy-land/laws/traversable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fantasy-land/index' {
  declare module.exports: $Exports<'fantasy-land'>;
}
declare module 'fantasy-land/index.js' {
  declare module.exports: $Exports<'fantasy-land'>;
}
declare module 'fantasy-land/internal/compose.js' {
  declare module.exports: $Exports<'fantasy-land/internal/compose'>;
}
declare module 'fantasy-land/internal/func.js' {
  declare module.exports: $Exports<'fantasy-land/internal/func'>;
}
declare module 'fantasy-land/internal/id.js' {
  declare module.exports: $Exports<'fantasy-land/internal/id'>;
}
declare module 'fantasy-land/internal/index.js' {
  declare module.exports: $Exports<'fantasy-land/internal/index'>;
}
declare module 'fantasy-land/internal/patch.js' {
  declare module.exports: $Exports<'fantasy-land/internal/patch'>;
}
declare module 'fantasy-land/internal/sum.js' {
  declare module.exports: $Exports<'fantasy-land/internal/sum'>;
}
declare module 'fantasy-land/laws/alt.js' {
  declare module.exports: $Exports<'fantasy-land/laws/alt'>;
}
declare module 'fantasy-land/laws/alternative.js' {
  declare module.exports: $Exports<'fantasy-land/laws/alternative'>;
}
declare module 'fantasy-land/laws/applicative.js' {
  declare module.exports: $Exports<'fantasy-land/laws/applicative'>;
}
declare module 'fantasy-land/laws/apply.js' {
  declare module.exports: $Exports<'fantasy-land/laws/apply'>;
}
declare module 'fantasy-land/laws/bifunctor.js' {
  declare module.exports: $Exports<'fantasy-land/laws/bifunctor'>;
}
declare module 'fantasy-land/laws/category.js' {
  declare module.exports: $Exports<'fantasy-land/laws/category'>;
}
declare module 'fantasy-land/laws/chain.js' {
  declare module.exports: $Exports<'fantasy-land/laws/chain'>;
}
declare module 'fantasy-land/laws/chainrec.js' {
  declare module.exports: $Exports<'fantasy-land/laws/chainrec'>;
}
declare module 'fantasy-land/laws/comonad.js' {
  declare module.exports: $Exports<'fantasy-land/laws/comonad'>;
}
declare module 'fantasy-land/laws/contravariant.js' {
  declare module.exports: $Exports<'fantasy-land/laws/contravariant'>;
}
declare module 'fantasy-land/laws/extend.js' {
  declare module.exports: $Exports<'fantasy-land/laws/extend'>;
}
declare module 'fantasy-land/laws/filterable.js' {
  declare module.exports: $Exports<'fantasy-land/laws/filterable'>;
}
declare module 'fantasy-land/laws/foldable.js' {
  declare module.exports: $Exports<'fantasy-land/laws/foldable'>;
}
declare module 'fantasy-land/laws/functor.js' {
  declare module.exports: $Exports<'fantasy-land/laws/functor'>;
}
declare module 'fantasy-land/laws/group.js' {
  declare module.exports: $Exports<'fantasy-land/laws/group'>;
}
declare module 'fantasy-land/laws/monad.js' {
  declare module.exports: $Exports<'fantasy-land/laws/monad'>;
}
declare module 'fantasy-land/laws/monoid.js' {
  declare module.exports: $Exports<'fantasy-land/laws/monoid'>;
}
declare module 'fantasy-land/laws/ord.js' {
  declare module.exports: $Exports<'fantasy-land/laws/ord'>;
}
declare module 'fantasy-land/laws/plus.js' {
  declare module.exports: $Exports<'fantasy-land/laws/plus'>;
}
declare module 'fantasy-land/laws/profunctor.js' {
  declare module.exports: $Exports<'fantasy-land/laws/profunctor'>;
}
declare module 'fantasy-land/laws/semigroup.js' {
  declare module.exports: $Exports<'fantasy-land/laws/semigroup'>;
}
declare module 'fantasy-land/laws/semigroupoid.js' {
  declare module.exports: $Exports<'fantasy-land/laws/semigroupoid'>;
}
declare module 'fantasy-land/laws/setoid.js' {
  declare module.exports: $Exports<'fantasy-land/laws/setoid'>;
}
declare module 'fantasy-land/laws/traversable.js' {
  declare module.exports: $Exports<'fantasy-land/laws/traversable'>;
}
