// flow-typed signature: cd11018384bf8d3847d1f1f1576af66d
// flow-typed version: <<STUB>>/fantasy-tuples_v^1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fantasy-tuples'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fantasy-tuples' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fantasy-tuples/fantasy-tuples' {
  declare module.exports: any;
}

declare module 'fantasy-tuples/src/nested' {
  declare module.exports: any;
}

declare module 'fantasy-tuples/src/tuples' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fantasy-tuples/fantasy-tuples.js' {
  declare module.exports: $Exports<'fantasy-tuples/fantasy-tuples'>;
}
declare module 'fantasy-tuples/src/nested.js' {
  declare module.exports: $Exports<'fantasy-tuples/src/nested'>;
}
declare module 'fantasy-tuples/src/tuples.js' {
  declare module.exports: $Exports<'fantasy-tuples/src/tuples'>;
}
