// flow-typed signature: f4e73d8106053510c0a17cf213c25698
// flow-typed version: <<STUB>>/google-translate-api_v^2.3.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'google-translate-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'google-translate-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'google-translate-api/languages' {
  declare module.exports: any;
}

declare module 'google-translate-api/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'google-translate-api/index' {
  declare module.exports: $Exports<'google-translate-api'>;
}
declare module 'google-translate-api/index.js' {
  declare module.exports: $Exports<'google-translate-api'>;
}
declare module 'google-translate-api/languages.js' {
  declare module.exports: $Exports<'google-translate-api/languages'>;
}
declare module 'google-translate-api/test.js' {
  declare module.exports: $Exports<'google-translate-api/test'>;
}
