// flow-typed signature: 026c39264c963cb37166b42214cd670a
// flow-typed version: <<STUB>>/live-server_v^1.2.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'live-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'live-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'live-server/live-server' {
  declare module.exports: any;
}

declare module 'live-server/middleware/example' {
  declare module.exports: any;
}

declare module 'live-server/middleware/spa-ignore-assets' {
  declare module.exports: any;
}

declare module 'live-server/middleware/spa' {
  declare module.exports: any;
}

declare module 'live-server/test/acceptance' {
  declare module.exports: any;
}

declare module 'live-server/test/cli' {
  declare module.exports: any;
}

declare module 'live-server/test/conf/https.conf' {
  declare module.exports: any;
}

declare module 'live-server/test/cors' {
  declare module.exports: any;
}

declare module 'live-server/test/data/middleware' {
  declare module.exports: any;
}

declare module 'live-server/test/htpasswd' {
  declare module.exports: any;
}

declare module 'live-server/test/https' {
  declare module.exports: any;
}

declare module 'live-server/test/middleware' {
  declare module.exports: any;
}

declare module 'live-server/test/mount' {
  declare module.exports: any;
}

declare module 'live-server/test/proxy' {
  declare module.exports: any;
}

declare module 'live-server/test/spa' {
  declare module.exports: any;
}

// Filename aliases
declare module 'live-server/index' {
  declare module.exports: $Exports<'live-server'>;
}
declare module 'live-server/index.js' {
  declare module.exports: $Exports<'live-server'>;
}
declare module 'live-server/live-server.js' {
  declare module.exports: $Exports<'live-server/live-server'>;
}
declare module 'live-server/middleware/example.js' {
  declare module.exports: $Exports<'live-server/middleware/example'>;
}
declare module 'live-server/middleware/spa-ignore-assets.js' {
  declare module.exports: $Exports<'live-server/middleware/spa-ignore-assets'>;
}
declare module 'live-server/middleware/spa.js' {
  declare module.exports: $Exports<'live-server/middleware/spa'>;
}
declare module 'live-server/test/acceptance.js' {
  declare module.exports: $Exports<'live-server/test/acceptance'>;
}
declare module 'live-server/test/cli.js' {
  declare module.exports: $Exports<'live-server/test/cli'>;
}
declare module 'live-server/test/conf/https.conf.js' {
  declare module.exports: $Exports<'live-server/test/conf/https.conf'>;
}
declare module 'live-server/test/cors.js' {
  declare module.exports: $Exports<'live-server/test/cors'>;
}
declare module 'live-server/test/data/middleware.js' {
  declare module.exports: $Exports<'live-server/test/data/middleware'>;
}
declare module 'live-server/test/htpasswd.js' {
  declare module.exports: $Exports<'live-server/test/htpasswd'>;
}
declare module 'live-server/test/https.js' {
  declare module.exports: $Exports<'live-server/test/https'>;
}
declare module 'live-server/test/middleware.js' {
  declare module.exports: $Exports<'live-server/test/middleware'>;
}
declare module 'live-server/test/mount.js' {
  declare module.exports: $Exports<'live-server/test/mount'>;
}
declare module 'live-server/test/proxy.js' {
  declare module.exports: $Exports<'live-server/test/proxy'>;
}
declare module 'live-server/test/spa.js' {
  declare module.exports: $Exports<'live-server/test/spa'>;
}
