// flow-typed signature: e998f7cc2c0cfa970d7c904eb9bac6b7
// flow-typed version: <<STUB>>/mocha-webpack_v^2.0.0-beta.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mocha-webpack/lib/cli/index' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/cli/parseArgv' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/cli/parseConfig' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/cli/requireWebpackConfig' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/createMochaWebpack' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/entry' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/MochaWebpack' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/reporters/base' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/runner/configureMocha' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/runner/loadReporter' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/runner/loadUI' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/runner/TestRunner' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/runner/testRunnerReporter' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/util/exists' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/util/glob' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/util/paths' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/util/registerRequireHook' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/utils' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/compiler/createCompiler' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/compiler/createWatchCompiler' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/compiler/registerInMemoryCompiler' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/compiler/registerReadyCallback' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/loader/entryLoader' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/loader/includeFilesLoader' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/plugin/buildProgressPlugin' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/types' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/util/createEntry' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/util/createStatsFormatter' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/util/formatUtil' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/util/getAffectedModuleIds' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/util/getBuildStats' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/util/sortChunks' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/cli/index' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/cli/parseArgv' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/cli/parseConfig' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/cli/requireWebpackConfig' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/createMochaWebpack' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/MochaWebpack' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/runner/configureMocha' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/runner/loadReporter' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/runner/loadUI' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/runner/TestRunner' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/runner/testRunnerReporter' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/util/exists' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/util/glob' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/util/paths' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/util/registerRequireHook' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/compiler/createCompiler' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/compiler/createWatchCompiler' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/compiler/registerInMemoryCompiler' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/compiler/registerReadyCallback' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/loader/entryLoader' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/loader/includeFilesLoader' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/plugin/buildProgressPlugin' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/types' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/util/createEntry' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/util/createStatsFormatter' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/util/formatUtil' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/util/getAffectedModuleIds' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/util/getBuildStats' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/util/sortChunks' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mocha-webpack/lib/cli/index.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/cli/index'>;
}
declare module 'mocha-webpack/lib/cli/parseArgv.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/cli/parseArgv'>;
}
declare module 'mocha-webpack/lib/cli/parseConfig.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/cli/parseConfig'>;
}
declare module 'mocha-webpack/lib/cli/requireWebpackConfig.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/cli/requireWebpackConfig'>;
}
declare module 'mocha-webpack/lib/createMochaWebpack.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/createMochaWebpack'>;
}
declare module 'mocha-webpack/lib/entry.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/entry'>;
}
declare module 'mocha-webpack/lib/MochaWebpack.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/MochaWebpack'>;
}
declare module 'mocha-webpack/lib/reporters/base.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/reporters/base'>;
}
declare module 'mocha-webpack/lib/runner/configureMocha.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/runner/configureMocha'>;
}
declare module 'mocha-webpack/lib/runner/loadReporter.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/runner/loadReporter'>;
}
declare module 'mocha-webpack/lib/runner/loadUI.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/runner/loadUI'>;
}
declare module 'mocha-webpack/lib/runner/TestRunner.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/runner/TestRunner'>;
}
declare module 'mocha-webpack/lib/runner/testRunnerReporter.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/runner/testRunnerReporter'>;
}
declare module 'mocha-webpack/lib/util/exists.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/util/exists'>;
}
declare module 'mocha-webpack/lib/util/glob.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/util/glob'>;
}
declare module 'mocha-webpack/lib/util/paths.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/util/paths'>;
}
declare module 'mocha-webpack/lib/util/registerRequireHook.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/util/registerRequireHook'>;
}
declare module 'mocha-webpack/lib/utils.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/utils'>;
}
declare module 'mocha-webpack/lib/webpack/compiler/createCompiler.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/compiler/createCompiler'>;
}
declare module 'mocha-webpack/lib/webpack/compiler/createWatchCompiler.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/compiler/createWatchCompiler'>;
}
declare module 'mocha-webpack/lib/webpack/compiler/registerInMemoryCompiler.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/compiler/registerInMemoryCompiler'>;
}
declare module 'mocha-webpack/lib/webpack/compiler/registerReadyCallback.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/compiler/registerReadyCallback'>;
}
declare module 'mocha-webpack/lib/webpack/loader/entryLoader.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/loader/entryLoader'>;
}
declare module 'mocha-webpack/lib/webpack/loader/includeFilesLoader.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/loader/includeFilesLoader'>;
}
declare module 'mocha-webpack/lib/webpack/plugin/buildProgressPlugin.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/plugin/buildProgressPlugin'>;
}
declare module 'mocha-webpack/lib/webpack/types.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/types'>;
}
declare module 'mocha-webpack/lib/webpack/util/createEntry.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/util/createEntry'>;
}
declare module 'mocha-webpack/lib/webpack/util/createStatsFormatter.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/util/createStatsFormatter'>;
}
declare module 'mocha-webpack/lib/webpack/util/formatUtil.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/util/formatUtil'>;
}
declare module 'mocha-webpack/lib/webpack/util/getAffectedModuleIds.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/util/getAffectedModuleIds'>;
}
declare module 'mocha-webpack/lib/webpack/util/getBuildStats.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/util/getBuildStats'>;
}
declare module 'mocha-webpack/lib/webpack/util/sortChunks.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/util/sortChunks'>;
}
declare module 'mocha-webpack/src/cli/index.js' {
  declare module.exports: $Exports<'mocha-webpack/src/cli/index'>;
}
declare module 'mocha-webpack/src/cli/parseArgv.js' {
  declare module.exports: $Exports<'mocha-webpack/src/cli/parseArgv'>;
}
declare module 'mocha-webpack/src/cli/parseConfig.js' {
  declare module.exports: $Exports<'mocha-webpack/src/cli/parseConfig'>;
}
declare module 'mocha-webpack/src/cli/requireWebpackConfig.js' {
  declare module.exports: $Exports<'mocha-webpack/src/cli/requireWebpackConfig'>;
}
declare module 'mocha-webpack/src/createMochaWebpack.js' {
  declare module.exports: $Exports<'mocha-webpack/src/createMochaWebpack'>;
}
declare module 'mocha-webpack/src/MochaWebpack.js' {
  declare module.exports: $Exports<'mocha-webpack/src/MochaWebpack'>;
}
declare module 'mocha-webpack/src/runner/configureMocha.js' {
  declare module.exports: $Exports<'mocha-webpack/src/runner/configureMocha'>;
}
declare module 'mocha-webpack/src/runner/loadReporter.js' {
  declare module.exports: $Exports<'mocha-webpack/src/runner/loadReporter'>;
}
declare module 'mocha-webpack/src/runner/loadUI.js' {
  declare module.exports: $Exports<'mocha-webpack/src/runner/loadUI'>;
}
declare module 'mocha-webpack/src/runner/TestRunner.js' {
  declare module.exports: $Exports<'mocha-webpack/src/runner/TestRunner'>;
}
declare module 'mocha-webpack/src/runner/testRunnerReporter.js' {
  declare module.exports: $Exports<'mocha-webpack/src/runner/testRunnerReporter'>;
}
declare module 'mocha-webpack/src/util/exists.js' {
  declare module.exports: $Exports<'mocha-webpack/src/util/exists'>;
}
declare module 'mocha-webpack/src/util/glob.js' {
  declare module.exports: $Exports<'mocha-webpack/src/util/glob'>;
}
declare module 'mocha-webpack/src/util/paths.js' {
  declare module.exports: $Exports<'mocha-webpack/src/util/paths'>;
}
declare module 'mocha-webpack/src/util/registerRequireHook.js' {
  declare module.exports: $Exports<'mocha-webpack/src/util/registerRequireHook'>;
}
declare module 'mocha-webpack/src/webpack/compiler/createCompiler.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/compiler/createCompiler'>;
}
declare module 'mocha-webpack/src/webpack/compiler/createWatchCompiler.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/compiler/createWatchCompiler'>;
}
declare module 'mocha-webpack/src/webpack/compiler/registerInMemoryCompiler.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/compiler/registerInMemoryCompiler'>;
}
declare module 'mocha-webpack/src/webpack/compiler/registerReadyCallback.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/compiler/registerReadyCallback'>;
}
declare module 'mocha-webpack/src/webpack/loader/entryLoader.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/loader/entryLoader'>;
}
declare module 'mocha-webpack/src/webpack/loader/includeFilesLoader.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/loader/includeFilesLoader'>;
}
declare module 'mocha-webpack/src/webpack/plugin/buildProgressPlugin.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/plugin/buildProgressPlugin'>;
}
declare module 'mocha-webpack/src/webpack/types.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/types'>;
}
declare module 'mocha-webpack/src/webpack/util/createEntry.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/util/createEntry'>;
}
declare module 'mocha-webpack/src/webpack/util/createStatsFormatter.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/util/createStatsFormatter'>;
}
declare module 'mocha-webpack/src/webpack/util/formatUtil.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/util/formatUtil'>;
}
declare module 'mocha-webpack/src/webpack/util/getAffectedModuleIds.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/util/getAffectedModuleIds'>;
}
declare module 'mocha-webpack/src/webpack/util/getBuildStats.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/util/getBuildStats'>;
}
declare module 'mocha-webpack/src/webpack/util/sortChunks.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/util/sortChunks'>;
}
