// flow-typed signature: 561b7b8b2247d08ab335b11010b3ee2f
// flow-typed version: <<STUB>>/ramda-fantasy_v^0.8.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ramda-fantasy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ramda-fantasy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ramda-fantasy/dist/ramda-fantasy' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/dist/ramda-fantasy.min' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/src/Either' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/src/Future' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/src/Identity' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/src/internal/util' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/src/IO' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/src/lift2' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/src/lift3' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/src/Maybe' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/src/Reader' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/src/State' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/src/Tuple' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/test/either.test' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/test/future.test' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/test/identity.test' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/test/io.test' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/test/lift2.test' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/test/lift3.test' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/test/maybe.test' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/test/reader.test' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/test/state.test' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/test/tuple.test' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/test/types' {
  declare module.exports: any;
}

declare module 'ramda-fantasy/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ramda-fantasy/dist/ramda-fantasy.js' {
  declare module.exports: $Exports<'ramda-fantasy/dist/ramda-fantasy'>;
}
declare module 'ramda-fantasy/dist/ramda-fantasy.min.js' {
  declare module.exports: $Exports<'ramda-fantasy/dist/ramda-fantasy.min'>;
}
declare module 'ramda-fantasy/index' {
  declare module.exports: $Exports<'ramda-fantasy'>;
}
declare module 'ramda-fantasy/index.js' {
  declare module.exports: $Exports<'ramda-fantasy'>;
}
declare module 'ramda-fantasy/src/Either.js' {
  declare module.exports: $Exports<'ramda-fantasy/src/Either'>;
}
declare module 'ramda-fantasy/src/Future.js' {
  declare module.exports: $Exports<'ramda-fantasy/src/Future'>;
}
declare module 'ramda-fantasy/src/Identity.js' {
  declare module.exports: $Exports<'ramda-fantasy/src/Identity'>;
}
declare module 'ramda-fantasy/src/internal/util.js' {
  declare module.exports: $Exports<'ramda-fantasy/src/internal/util'>;
}
declare module 'ramda-fantasy/src/IO.js' {
  declare module.exports: $Exports<'ramda-fantasy/src/IO'>;
}
declare module 'ramda-fantasy/src/lift2.js' {
  declare module.exports: $Exports<'ramda-fantasy/src/lift2'>;
}
declare module 'ramda-fantasy/src/lift3.js' {
  declare module.exports: $Exports<'ramda-fantasy/src/lift3'>;
}
declare module 'ramda-fantasy/src/Maybe.js' {
  declare module.exports: $Exports<'ramda-fantasy/src/Maybe'>;
}
declare module 'ramda-fantasy/src/Reader.js' {
  declare module.exports: $Exports<'ramda-fantasy/src/Reader'>;
}
declare module 'ramda-fantasy/src/State.js' {
  declare module.exports: $Exports<'ramda-fantasy/src/State'>;
}
declare module 'ramda-fantasy/src/Tuple.js' {
  declare module.exports: $Exports<'ramda-fantasy/src/Tuple'>;
}
declare module 'ramda-fantasy/test/either.test.js' {
  declare module.exports: $Exports<'ramda-fantasy/test/either.test'>;
}
declare module 'ramda-fantasy/test/future.test.js' {
  declare module.exports: $Exports<'ramda-fantasy/test/future.test'>;
}
declare module 'ramda-fantasy/test/identity.test.js' {
  declare module.exports: $Exports<'ramda-fantasy/test/identity.test'>;
}
declare module 'ramda-fantasy/test/io.test.js' {
  declare module.exports: $Exports<'ramda-fantasy/test/io.test'>;
}
declare module 'ramda-fantasy/test/lift2.test.js' {
  declare module.exports: $Exports<'ramda-fantasy/test/lift2.test'>;
}
declare module 'ramda-fantasy/test/lift3.test.js' {
  declare module.exports: $Exports<'ramda-fantasy/test/lift3.test'>;
}
declare module 'ramda-fantasy/test/maybe.test.js' {
  declare module.exports: $Exports<'ramda-fantasy/test/maybe.test'>;
}
declare module 'ramda-fantasy/test/reader.test.js' {
  declare module.exports: $Exports<'ramda-fantasy/test/reader.test'>;
}
declare module 'ramda-fantasy/test/state.test.js' {
  declare module.exports: $Exports<'ramda-fantasy/test/state.test'>;
}
declare module 'ramda-fantasy/test/tuple.test.js' {
  declare module.exports: $Exports<'ramda-fantasy/test/tuple.test'>;
}
declare module 'ramda-fantasy/test/types.js' {
  declare module.exports: $Exports<'ramda-fantasy/test/types'>;
}
declare module 'ramda-fantasy/test/utils.js' {
  declare module.exports: $Exports<'ramda-fantasy/test/utils'>;
}
