// flow-typed signature: 597dbebeac001714e5e113a171719392
// flow-typed version: <<STUB>>/react-highlight-words_v^0.11.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-highlight-words'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-highlight-words' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-highlight-words/build/static/main' {
  declare module.exports: any;
}

declare module 'react-highlight-words/dist/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-highlight-words/build/static/main.js' {
  declare module.exports: $Exports<'react-highlight-words/build/static/main'>;
}
declare module 'react-highlight-words/dist/main.js' {
  declare module.exports: $Exports<'react-highlight-words/dist/main'>;
}
