// flow-typed signature: aad83647619b1b47f7cfc1374c4b934a
// flow-typed version: <<STUB>>/react-scroll_v^1.7.7/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-scroll/modules/__tests__/animate-scroll-test' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/__tests__/animation-type-unit-tests' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/__tests__/element-test' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/__tests__/events-test' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/__tests__/link-test' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/__tests__/page-test' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/__tests__/scroll-cancellation-test' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/components/Button' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/components/Element' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/components/Link' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/index' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/mixins/animate-scroll' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/mixins/cancel-events' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/mixins/Helpers' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/mixins/passive-event-listeners' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/mixins/scroll-element' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/mixins/scroll-events' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/mixins/scroll-hash' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/mixins/scroll-link' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/mixins/scroll-spy' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/mixins/scroller' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/mixins/smooth' {
  declare module.exports: any;
}

declare module 'react-scroll/modules/mixins/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-scroll/modules/__tests__/animate-scroll-test.js' {
  declare module.exports: $Exports<'react-scroll/modules/__tests__/animate-scroll-test'>;
}
declare module 'react-scroll/modules/__tests__/animation-type-unit-tests.js' {
  declare module.exports: $Exports<'react-scroll/modules/__tests__/animation-type-unit-tests'>;
}
declare module 'react-scroll/modules/__tests__/element-test.js' {
  declare module.exports: $Exports<'react-scroll/modules/__tests__/element-test'>;
}
declare module 'react-scroll/modules/__tests__/events-test.js' {
  declare module.exports: $Exports<'react-scroll/modules/__tests__/events-test'>;
}
declare module 'react-scroll/modules/__tests__/link-test.js' {
  declare module.exports: $Exports<'react-scroll/modules/__tests__/link-test'>;
}
declare module 'react-scroll/modules/__tests__/page-test.js' {
  declare module.exports: $Exports<'react-scroll/modules/__tests__/page-test'>;
}
declare module 'react-scroll/modules/__tests__/scroll-cancellation-test.js' {
  declare module.exports: $Exports<'react-scroll/modules/__tests__/scroll-cancellation-test'>;
}
declare module 'react-scroll/modules/components/Button.js' {
  declare module.exports: $Exports<'react-scroll/modules/components/Button'>;
}
declare module 'react-scroll/modules/components/Element.js' {
  declare module.exports: $Exports<'react-scroll/modules/components/Element'>;
}
declare module 'react-scroll/modules/components/Link.js' {
  declare module.exports: $Exports<'react-scroll/modules/components/Link'>;
}
declare module 'react-scroll/modules/index.js' {
  declare module.exports: $Exports<'react-scroll/modules/index'>;
}
declare module 'react-scroll/modules/mixins/animate-scroll.js' {
  declare module.exports: $Exports<'react-scroll/modules/mixins/animate-scroll'>;
}
declare module 'react-scroll/modules/mixins/cancel-events.js' {
  declare module.exports: $Exports<'react-scroll/modules/mixins/cancel-events'>;
}
declare module 'react-scroll/modules/mixins/Helpers.js' {
  declare module.exports: $Exports<'react-scroll/modules/mixins/Helpers'>;
}
declare module 'react-scroll/modules/mixins/passive-event-listeners.js' {
  declare module.exports: $Exports<'react-scroll/modules/mixins/passive-event-listeners'>;
}
declare module 'react-scroll/modules/mixins/scroll-element.js' {
  declare module.exports: $Exports<'react-scroll/modules/mixins/scroll-element'>;
}
declare module 'react-scroll/modules/mixins/scroll-events.js' {
  declare module.exports: $Exports<'react-scroll/modules/mixins/scroll-events'>;
}
declare module 'react-scroll/modules/mixins/scroll-hash.js' {
  declare module.exports: $Exports<'react-scroll/modules/mixins/scroll-hash'>;
}
declare module 'react-scroll/modules/mixins/scroll-link.js' {
  declare module.exports: $Exports<'react-scroll/modules/mixins/scroll-link'>;
}
declare module 'react-scroll/modules/mixins/scroll-spy.js' {
  declare module.exports: $Exports<'react-scroll/modules/mixins/scroll-spy'>;
}
declare module 'react-scroll/modules/mixins/scroller.js' {
  declare module.exports: $Exports<'react-scroll/modules/mixins/scroller'>;
}
declare module 'react-scroll/modules/mixins/smooth.js' {
  declare module.exports: $Exports<'react-scroll/modules/mixins/smooth'>;
}
declare module 'react-scroll/modules/mixins/utils.js' {
  declare module.exports: $Exports<'react-scroll/modules/mixins/utils'>;
}
