// flow-typed signature: 7721051531e826d917117e18872976fd
// flow-typed version: <<STUB>>/reduce-reducers_v^0.1.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reduce-reducers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reduce-reducers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reduce-reducers/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reduce-reducers/dist/index.js' {
  declare module.exports: $Exports<'reduce-reducers/dist/index'>;
}
