// flow-typed signature: 2816201f51e04132e0faf22b536b0221
// flow-typed version: <<STUB>>/yaml-loader_v^0.5.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yaml-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yaml-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'yaml-loader/index' {
  declare module.exports: $Exports<'yaml-loader'>;
}
declare module 'yaml-loader/index.js' {
  declare module.exports: $Exports<'yaml-loader'>;
}
