[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "default-src 'self' mon-entreprise.fr; style-src 'self' 'unsafe-inline' mon-entreprise.zammad.com; connect-src 'self' *.incubateur.net raw.githubusercontent.com tm.urssaf.fr mon-entreprise.zammad.com api.recherche-entreprises.fabrique.social.gouv.fr geo.api.gouv.fr *.algolia.net *.algolianet.com; form-action 'self' *.sibforms.com *.incubateur.net mon-entreprise.zammad.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' tm.urssaf.fr *.incubateur.net stonly.com code.jquery.com mon-entreprise.zammad.com polyfill.io; img-src 'self' data: tm.urssaf.fr user-images.githubusercontent.com; frame-src 'self' https://www.youtube-nocookie.com https://codesandbox.io https://place-des-entreprises.beta.gouv.fr https://reso-staging.osc-fr1.scalingo.io https://stackblitz.com"

## Scalingo proxy for API
[[redirects]]
  from = "/api/*"
  to = ":API_URL/api/:splat"
  status = 200

## Twemoji proxy for client privacy #1219
[[redirects]]
  from = "/twemoji/*"
  to = "https://twemoji.maxcdn.com/:splat"
  status = 200

############
# Redirects following architectural changes

# :SITE_<name> is a placeholder replaced before deploy (depends on the environment)

# FR | coronavirus -> simulateurs/chômage-partiel
[[redirects]]
  from=":SITE_FR/coronavirus"
  to=":SITE_FR/simulateurs/ch%C3%B4mage-partiel"
  status = 301

[[redirects]]
  from=":SITE_FR/%C3%A9conomie-collaborative"
  to=":SITE_FR/simulateurs/%C3%A9conomie-collaborative"
  status = 301

# FR | salarié -> salaire-brut-net
[[redirects]]
  from=":SITE_FR/simulateurs/salari%C3%A9"
  to=":SITE_FR/simulateurs/salaire-brut-net"
  status = 301

# FR | assimilé-salarié -> sasu
[[redirects]]
  from=":SITE_FR/simulateurs/assimil%C3%A9-salari%C3%A9"
  to=":SITE_FR/simulateurs/sasu"
  status = 301

# FR | dirigeant-sasu -> sasu
[[redirects]]
  from=":SITE_FR/simulateurs/dirigeant-sasu"
  to=":SITE_FR/simulateurs/sasu"
  status = 301

# FR | s%C3%A9curit%C3%A9-sociale/auto-entrepreneur -> simulateurs/auto-entrepreneur
[[redirects]]
  from=":SITE_FR/s%C3%A9curit%C3%A9-sociale/auto-entrepreneur"
  to=":SITE_FR/simulateurs/auto-entrepreneur"
  status = 301

# FR | sécurité-social/salarié -> simulateurs/salaire-brut-net
[[redirects]]
  from=":SITE_FR/s%C3%A9curit%C3%A9-sociale/salari%C3%A9"
  to=":SITE_FR/simulateurs/salaire-brut-net"
  statys = 301

# FR | sécurité-social/salarié -> simulateurs/salaire-brut-net
[[redirects]]
  from=":SITE_FR/s%C3%A9curit%C3%A9-sociale/salari%C3%A9"
  to=":SITE_FR/simulateurs/salaire-brut-net"
  status = 301

# SEO redirect
[[redirects]]
  from = ":SITE_FR/documentation/contrat-salari%C3%A9/salaire/*"
  to = ":SITE_FR/documentation/contrat-salari%C3%A9/r%C3%A9mun%C3%A9ration/:splat"
  status = 301

# EN | sasu-chairman -> sasu
[[redirects]]
  from=":SITE_EN/simulateurs/sasu-chairman"
  to=":SITE_EN/simulateurs/sasu"
  status = 301

# FR | intégration -> développeur
[[redirects]]
  from=":SITE_FR/int%C3%A9gration/*"
  to=":SITE_FR/d%C3%A9veloppeur/:splat"
  status = 301

# EN | integration -> developer
[[redirects]]
  from=":SITE_EN/integration/*"
  to=":SITE_EN/developer/:splat"
  status = 301


############
# Prerender will be added by script build:prerender
#[prerender]#

############
# Redirects for single page app config


# Mon-entreprise.fr
[[redirects]]
  from = ":SITE_FR/robots.txt"
  to = "/robots.fr.txt"
  status = 200

[[redirects]]
  from = ":SITE_FR/sitemap.txt"
  to = "/sitemap.fr.txt"
  status = 200

[[redirects]]
  from = ":SITE_FR/dev/storybook"
  to = "/dev/storybook/index.html"
  status = 200

[[redirects]]
  from = ":SITE_FR/*"
  to = "/mon-entreprise.html"
  status = 200


# Mycompanyinfrance


[[redirects]]
  from = ":SITE_EN/robots.txt"
  to = "/robots.en.txt"
  status = 200

[[redirects]]
  from = ":SITE_EN/sitemap.txt"
  to = "/sitemap.en.txt"
  status = 200

[[redirects]]
  from = ":SITE_EN/dev/storybook"
  to = "/dev/storybook/index.html"
  status = 200

[[redirects]]
  from = ":SITE_EN/*"
  to = "/infrance.html"
  status = 200
