// flow-typed signature: 4f1a1f0e59a8d0ff82c1bb03fd4c4ba8
// flow-typed version: <<STUB>>/@babel/plugin-proposal-decorators_v=7.0.0-beta.46/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-decorators'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-decorators' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-decorators/lib/index' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-decorators/lib/transformer-legacy' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-decorators/lib/transformer' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-decorators/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-decorators/lib/index'>;
}
declare module '@babel/plugin-proposal-decorators/lib/transformer-legacy.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-decorators/lib/transformer-legacy'>;
}
declare module '@babel/plugin-proposal-decorators/lib/transformer.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-decorators/lib/transformer'>;
}
