// flow-typed signature: bea553b9f40c2a5d249e0058c67a760d
// flow-typed version: <<STUB>>/@babel/plugin-syntax-decorators_v=7.0.0-beta.46/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-syntax-decorators'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-syntax-decorators' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-syntax-decorators/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-syntax-decorators/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-syntax-decorators/lib/index'>;
}
