name: '🐛 Rapport de bug'
description: Signaler un bug reproductible.
title: '🐛 <title>'
labels: ['🐛 bug']
body:
  - type: markdown
    attributes:
      value: Merci de lire et de suivre les instructions avant de soumettre un ticket
  - type: markdown
    attributes:
      value: |
        - Soyez sure que votre ticket n'est pas déjà [rapporté](https://github.com/betagouv/mon-entreprise/issues?utf8=%E2%9C%93&q=is%3Aissue).
  - type: textarea
    id: description
    attributes:
      label: 'Description du problème'
      description: Une description claire et concise du bug.
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: 'URL de la page'
      description: Liens vers la page où le bug a été rencontré.
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: 'Reproduction du problème'
      description: Étapes pour reproduire le problème.
      placeholder: |
        1. Aller sur '...'
        2. Cliquer sur '....'
        3. Défiler jusqu'à '....'
        4. Voir l'erreur
      render: bash
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: 'Attendu'
      description: Une description claire et concise de ce que vous attendiez.
    validations:
      required: false
  - type: input
    id: browser
    attributes:
      label: 'Informations sur le navigateur, OS, ...'
      description: Merci de mettre un lien de [whatsmybrowser](https://www.whatsmybrowser.org/)
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: 'Contexte supplémentaire'
      description: Ajoutez ici tout autre contexte ou capture d'écran concernant le ticket.
      render: bash
    validations:
      required: false

