name: '🏓 Retour utilisateur'
description: Signaler un retour utilisateur.
title: '🏓 <title>'
labels: ['🏓 retour utilisateur']
body:
  - type: markdown
    attributes:
      value: Merci de lire et de suivre les instructions avant de soumettre un ticket
  - type: markdown
    attributes:
      value: |
        - Lisez toute notre documentation, en particulier le [README](https://github.com/betagouv/mon-entreprise/blob/master/README.md). Elles peuvent contenir des informations qui vous aideront à résoudre votre problème.
        - Soyez sure que votre ticket n'est pas déjà [rapporté](https://github.com/betagouv/mon-entreprise/issues?utf8=%E2%9C%93&q=is%3Aissue).
  - type: textarea
    id: description
    attributes:
      label: 'Description du retour utilisateur'
      description: Une description claire et concise du retour.
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: 'URL de la page'
      description: Liens vers la page.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: 'Contexte supplémentaire'
      description: Ajoutez ici tout autre contexte ou capture d'écran concernant le ticket.
      render: bash
    validations:
      required: false
