situation:
  artiste-auteur: oui
  dirigeant:
    applicable si: non

unité par défaut: €/an

objectifs cachés:
  - artiste-auteur . cotisations
  - artiste-auteur . revenus
  - artiste-auteur . cotisations . IRCEC
questions:
  liste:
    - artiste-auteur . revenus . BNC . micro-bnc
    - artiste-auteur . cotisations . option surcotisation
    - artiste-auteur . cotisations . IRCEC . cotisation RAAP . taux réduit
    - artiste-auteur . cotisations . IRCEC . profession
