objectifs:
  - salarié . contrat . salaire brut

objectifs cachés:
  - salarié . rémunération . net
  - salarié . prix du travail

questions:
  liste:
    - salarié . activité partielle
    - salarié . temps de travail
    - établissement . localisation

unité par défaut: €/mois

situation:
  dirigeant: non
  salarié . activité partielle: oui
  salarié . complémentaire santé:
    applicable si: non
