objectifs:
  - dirigeant . rémunération . totale
  - salarié . cotisations
  - salarié . rémunération . net
  - impôt . montant
  - salarié . rémunération . net après impôt

questions:
  à l'affiche:
    ACRE: entreprise . ACRE
    Commune: établissement . localisation
    Avantages en nature: salarié . rémunération . avantages en nature
    Impôt sur le revenu: impôt . méthode de calcul

  liste noire:
    - entreprise . charges
    - entreprise . imposition
    - entreprise . rémunération du dirigeant
    - entreprise . association non lucrative
  non prioritaires:
    - entreprise . non assujettie à TVA
    - entreprise . effectif
    - établissement . localisation
    - entreprise . ratio alternants
    - salarié . complémentaire santé
    - salarié . régime des impatriés

unité par défaut: €/an
situation:
  entreprise . catégorie juridique: "'SAS'"
  entreprise . résultat fiscal: 0 €/an

  #TODO : en attendant que la transitivité du remplacement soit implémentée (https://github.com/betagouv/publicodes/issues/55)
  salarié . activité partielle: non
  salarié . déduction forfaitaire spécifique: non
