objectifs:
  - entreprise . chiffre d'affaires
  - dirigeant . rémunération . totale
  - dirigeant . rémunération . net
  - dirigeant . rémunération . net . après impôt

questions:
  à l'affiche:
    Type d'activité: entreprise . activité
    Micro-fiscal: entreprise . imposition . régime . micro-entreprise
    Date de création: entreprise . date de création
    ACRE: entreprise . exonérations . ACRE
    Contrats Madelins: dirigeant . indépendant . cotisations facultatives
    Conjoint collaborateur: dirigeant . indépendant . conjoint collaborateur
    Impôt sur le revenu: impôt . méthode de calcul
  liste noire:
    - entreprise . charges
    - entreprise . exercice . début
    - entreprise . exercice . fin
    - entreprise . catégorie juridique
    - entreprise . imposition . régime
  non prioritaires:
    - dirigeant . indépendant . cotisations facultatives
    - dirigeant . indépendant . IJSS
    - dirigeant . indépendant . PL . PAMC . IJSS
    - dirigeant . indépendant . PL . CNAVPL . exonération incapacité
    - dirigeant . indépendant . cotisations et contributions . exonérations . pension invalidité
    - entreprise . ZFU
    - entreprise . salariés . effectif
    - entreprise . activité . débit de tabac

unité par défaut: €/an
situation:
  dirigeant . régime social: "'indépendant'"
  entreprise . imposition: "'IR'"
