objectifs:
  - entreprise . chiffre d'affaires
  - dirigeant . rémunération . totale
  - dirigeant . rémunération . nette
  - dirigeant . rémunération . nette après impôt

questions:
  à l'affiche:
    Type d'activité: entreprise . activité
    Micro-fiscal: entreprise . imposition . régime . micro-entreprise
    Date de création: entreprise . date de création
    ACRE: entreprise . ACRE
    Contrats Madelins: dirigeant . indépendant . cotisations facultatives
    Conjoint collaborateur: dirigeant . indépendant . conjoint collaborateur
    Impôt sur le revenu: impôt . méthode de calcul
  liste noire:
    - entreprise . charges
    - entreprise . exercice . début
    - entreprise . exercice . fin
    - entreprise . catégorie juridique
    - entreprise . imposition . régime
  liste:
    - entreprise
    - établissement
    - dirigeant . indépendant
    - situation personnelle
    - impôt
  non prioritaires:
    - dirigeant . indépendant . IJSS
    - dirigeant . indépendant . cotisations et contributions . exonérations
    - entreprise . ZFU
    - entreprise . effectif
    - entreprise . activité . débit de tabac

unité par défaut: €/an
situation:
  dirigeant . régime social: "'indépendant'"
