objectifs:
  - entreprise . chiffre d'affaires
  - entreprise . charges
  - dirigeant . indépendant . cotisations et contributions
  - dirigeant . rémunération . nette
  - impôt . montant
  - dirigeant . rémunération . nette après impôt
  - protection sociale . retraite . complémentaire indépendants . points acquis
  - protection sociale . retraite . base . trimestres . indépendant
  - protection sociale . retraite . CNAVPL

questions:
  liste noire:
    - entreprise . charges
  liste:
    - entreprise . activité
    - dirigeant . indépendant . PL . métier
    - entreprise . date de création
    - entreprise . ACRE
    - dirigeant . indépendant
    - entreprise
    - établissement
    - situation personnelle
    - impôt
  non prioritaires:
    - dirigeant . indépendant . cotisations facultatives
    - dirigeant . indépendant . IJSS
    - dirigeant . indépendant . cotisations et contributions . exonérations
    - dirigeant . indépendant . revenus étrangers
    - entreprise . ZFU
    - entreprise . effectif
unité par défaut: €/an
situation:
  entreprise . activité: "'libérale'"
  entreprise . catégorie juridique: "'EI'"
  entreprise . catégorie juridique . EI . responsabilité limité: non
  entreprise . catégorie juridique . EI . auto-entrepreneur: non
