objectifs:
  - entreprise . chiffre d'affaires
  - entreprise . charges
  - dirigeant . indépendant . cotisations et contributions
  - dirigeant . rémunération . net
  - impôt . montant
  - dirigeant . rémunération . net . après impôt
  - protection sociale . retraite . complémentaire indépendants . points acquis
  - protection sociale . retraite . base . trimestres . indépendant
  - protection sociale . retraite . CNAVPL

questions:
  liste noire:
    - entreprise . charges
    - entreprise . imposition . régime
  liste:
    - entreprise . activité . nature
    - dirigeant . indépendant . PL . métier
    - '' # Toutes les autres questions
  non prioritaires:
    - dirigeant . indépendant . cotisations facultatives
    - dirigeant . indépendant . IJSS
    - dirigeant . indépendant . PL . PAMC . IJSS
    - dirigeant . indépendant . PL . CNAVPL . exonération incapacité
    - dirigeant . indépendant . cotisations et contributions . exonérations . pension invalidité

unité par défaut: €/an
situation:
  entreprise . activité . nature: "'libérale'"
  entreprise . catégorie juridique: "'EI'"
  entreprise . imposition: "'IR'"
  entreprise . catégorie juridique . EI . auto-entrepreneur: non
