objectifs:
  - déclaration charge sociales . résultat . cotisations obligatoires
  - déclaration charge sociales . résultat . total charges sociales déductible
  - déclaration charge sociales . résultat . revenu net fiscal
  - déclaration charge sociales . résultat . assiette sociale
situation:
  déclaration charge sociales: oui
  dirigeant . régime social: "'indépendant'"
  date: 01/01/2021
  dirigeant . indépendant . PL . CIPAV: non # TODO En attendant la transitivité des remplacements
  impôt: non

unité par défaut: '€'
