objectifs:
  - aide déclaration revenu indépendant 2020 . revenu net fiscal
  - aide déclaration revenu indépendant 2020 . CSG déductible
  - aide déclaration revenu indépendant 2020 . cotisations obligatoires
  - aide déclaration revenu indépendant 2020 . CFP
  - aide déclaration revenu indépendant 2020 . réduction covid . montant
  - aide déclaration revenu indépendant 2020 . total charges sociales déductible
  - aide déclaration revenu indépendant 2020 . assiette sociale

situation:
  dirigeant: "'indépendant'"
  aide déclaration revenu indépendant 2020: oui
  dirigeant . indépendant . PL . CIPAV: non # TODO En attendant la transitivité des remplacements
unité par défaut: '€/an'
