objectifs:
  - dirigeant . auto-entrepreneur . chiffre d'affaires
  - dirigeant . auto-entrepreneur . cotisations et contributions
  - dirigeant . auto-entrepreneur . net de cotisations
  - dirigeant . rémunération . impôt
  - dirigeant . auto-entrepreneur . net après impôt

questions:
  à l'affiche:
    Type d'activité: entreprise . activité
    Versement libératoire: dirigeant . auto-entrepreneur . impôt . versement libératoire
    Impôt sur le revenu: impôt . méthode de calcul
    ACRE: entreprise . ACRE
  liste:
    - entreprise
    - dirigeant
    - impôt
    - établissement
    - situation personnelle
  non prioritaires:
    - établissement . localisation
  liste noire:
    - entreprise . charges
    - entreprise . chiffre d'affaires

unité par défaut: €/an
situation:
  entreprise . activité . mixte: non
  dirigeant: "'auto-entrepreneur'"
