objectifs:
  - dirigeant . auto-entrepreneur . chiffre d'affaires
  - dirigeant . auto-entrepreneur . net de cotisations
  - dirigeant . auto-entrepreneur . net après impôt
  - dirigeant . auto-entrepreneur . cotisations et contributions
  - dirigeant . auto-entrepreneur . net après impôt . impôt

questions:
  à l'affiche:
    Type d'activité: entreprise . activité
    Versement libératoire: dirigeant . auto-entrepreneur . impôt . versement libératoire
    Impôt sur le revenu: impôt . méthode de calcul
    ACRE: entreprise . ACRE
  liste:
    - entreprise
    - dirigeant
    - impôt
    - établissement
    - situation personnelle
  non prioritaires:
    - établissement . localisation
  liste noire:
    - entreprise . charges
    - entreprise . chiffre d'affaires . vente restauration hébergement
    - entreprise . chiffre d'affaires . prestations de service . BIC
    - entreprise . chiffre d'affaires . prestations de service . BNC
unité par défaut: €/an
situation:
  entreprise . activité . mixte: non
  dirigeant: "'auto-entrepreneur'"
