objectifs:
  - contrat salarié . rémunération . brut de base

objectifs cachés:
  - contrat salarié . rémunération . net
  - contrat salarié . prix du travail

questions:
  liste:
    - contrat salarié . activité partielle
    - contrat salarié . temps de travail
    - établissement . localisation

unité par défaut: €/mois
situation:
  dirigeant: non
  contrat salarié . activité partielle: oui
  contrat salarié . médecine du travail: non
  contrat salarié . complémentaire santé: non
