titre: |
  Calcul du revenu du travailleur indépendant ou dirigeant d'entreprise après paiement des cotisations et de l'impôt sur le revenu.

objectifs:
  - contrat salarié . rémunération . net
  - dirigeant . indépendant . revenu net de cotisations
  - dirigeant . auto-entrepreneur . net de cotisations
  - protection sociale . retraite
  - protection sociale . retraite . trimestres validés
  - protection sociale . santé . indemnités journalières

questions:
  liste:
    - dirigeant . rémunération totale
    - entreprise . charges
    - entreprise . activité
unité par défaut: €/an
situation:
  dirigeant: "'auto-entrepreneur'"
  entreprise . activité . mixte: non
  contrat salarié . ATMP . taux réduit: oui
