openapi: 3.0.0

info:
  title: Mon-entreprise API
  version: beta
  description: |
    Cet API expose les règles Publicodes de [mon-entreprise](https://mon-entreprise.urssaf.fr/).

    Pour plus d'informations, consultez [notre documentation](/d%C3%A9veloppeur/api).

servers:
  - url: /api/v1/

paths: {}
