openapi: 3.0.0

info:
  title: Mon-entreprise API
  version: beta
  description: |
    Cet API expose les règles Publicodes de [mon-entreprise](https://mon-entreprise.urssaf.fr/).

    Pour plus d'informations, consultez [notre documentation](/d%C3%A9veloppeur/api).

servers:
  - url: /api/v1/

paths:
  /evaluate:
    post:
      requestBody:
        content:
          application/json:
            examples:
              SalaireBrutEnNet:
                value:
                  {
                    'situation':
                      {
                        'salarié . contrat . salaire brut':
                          { 'valeur': 4200, 'unité': '€ / mois' },
                        'salarié . contrat': "'CDI'",
                      },
                    'expressions':
                      ['salarié . rémunération . net à payer avant impôt'],
                  }
              MicroEntreprise:
                value:
                  {
                    situation:
                      {
                        "dirigeant . auto-entrepreneur . chiffre d'affaires": '42000 €/an',
                        'entreprise . activité': "'libérale'",
                        'entreprise . activité . libérale . réglementée': 'non',
                        'entreprise . catégorie juridique': "'EI'",
                        'entreprise . catégorie juridique . EI . auto-entrepreneur': 'oui',
                        'dirigeant . auto-entrepreneur . impôt . versement libératoire': 'non',
                        'impôt . méthode de calcul': "'taux neutre'",
                      },
                    expressions:
                      [
                        {
                          'valeur': 'dirigeant . auto-entrepreneur . cotisations et contributions',
                          'unité': '€/an',
                        },
                        'dirigeant . rémunération . impôt',
                        'dirigeant . auto-entrepreneur . net après impôt',
                      ],
                  }
  /rules/{rule}:
    get:
      parameters:
        - examples:
            SalaireNet:
              value: 'salarié . rémunération . net à payer avant impôt'
            Impot:
              value: 'impôt . méthode de calcul'
