plafond sécurité sociale:
  description: Le plafond de Sécurité sociale est le montant maximum des rémunérations à prendre en compte pour le calcul de certaines cotisations.
  acronyme: PSS
  valeur: 3428 €/mois
  références:
    Urssaf.fr: https://www.urssaf.fr/portail/home/taux-et-baremes/plafonds.html
    arrêté 2021: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000042748904
  note: Le plafond de la Sécurité sociale n'a pas été revalorisé en 2021 par rapport à 2020.

  avec:
    horaire:
      acronyme: PHSS
      valeur: plafond sécurité sociale / 1607 heures/an
      arrondi: oui
      unité: €/heures
      références:
        Article D242-19 du code de la sécurité sociale: https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000033516173&cidTexte=LEGITEXT000006073189

    journalier:
      acronyme: PJSS
      valeur: plafond sécurité sociale / 218 jours/an
      arrondi: oui
      unité: €/jour
      références:
        Article D242-17 du code de la sécurité sociale: https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006073189&idArticle=LEGIARTI000006736124

SMIC:
  unité: €/mois
  produit:
    assiette: durée légale du travail . mensuelle
    facteur: SMIC . horaire
  références:
    décret: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000042677359?r=s75zUOEVpR

SMIC . net imposable:
  titre global: SMIC net imposable
  description: Montant du SMIC net imposable pour un temps plein.
  recalcul:
    règle: salarié . rémunération . net . imposable . sans déductions
    avec:
      salarié: oui
      salarié . contrat . salaire brut: SMIC
  références:
    barème PAS: https://bofip.impots.gouv.fr/bofip/11255-PGP.html

SMIC . horaire:
  titre global: SMIC horaire
  variations:
    - si: établissement . commune . département . outre-mer . Mayotte
      alors:
        variations:
          - si: date >= 01/08/2022
            alors: 8.35 €/heures
          - si: date >= 01/05/2022
            alors: 8.19 €/heures
          - si: date >= 01/2022
            alors: 7.98 €/heures
          - si: date >= 01/10/2021
            alors: 7.91 €/heures
          - si: date >= 01/2021
            alors: 7.74 €/heures
    - sinon:
        variations:
          - si: date >= 01/08/2022
            alors: 11.07 €/heures
          - si: date >= 01/05/2022
            alors: 10.85 €/heures
          - si: date >= 01/2022
            alors: 10.57 €/heures
          - si: date >= 01/10/2021
            alors: 10.48 €/heures
          - si: date >= 01/2021
            alors: 10.25 €/heures
  note: |
    En principe et sauf « coup de pouce », le SMIC est revalorisé au 1er janvier
    de chaque année. Toutefois une revalorisation doit intervenir en cours
    d'année si l'indice des prix de référence a augmenté de 2% ou plus depuis la
    dernière revalorisation du SMIC.
  références:
    décret: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000046113517
    service-public.fr: https://www.service-public.fr/particuliers/vosdroits/F2300
  avec:
    début d'année:
      titre: en début d'année
      recalcul:
        règle: SMIC . horaire
        avec:
          date: période . début d'année

durée légale du travail:
  valeur: 35 heures/semaine
  avec:
    mensuelle: durée légale du travail * période . semaines par mois
  références:
    Code du travail numérique: https://code.travail.gouv.fr/fiche-ministere-travail/la-duree-legale-du-travail
