date: 01/08/2022
période: oui
période . jours ouvrés moyen par mois:
  formule: 21 jour ouvré/mois
  note: On retient 21 comme nombre de jours ouvrés moyen par mois

période . semaines par mois:
  unité: semaines/mois
  formule: 52 semaines/an / 12 mois/an

# TODO: This is fragile, we should have a more robust and generic way of
# calculating the beginning and the end of the year of a given date.
période . début d'année:
  variations:
    - si: date >= 01/2022
      alors: 01/01/2022
    - si: date >= 01/2021
      alors: 01/01/2021

période . fin d'année:
  variations:
    - si: date <= 31/12/2021
      alors: 31/12/2021
    - si: date <= 31/12/2022
      alors: 31/12/2022

plafond sécurité sociale temps plein:
  description: Le plafond de Sécurité sociale est le montant maximum des rémunérations à prendre en compte pour le calcul de certaines cotisations.
  acronyme: PSS
  formule: 3428 €/mois
  références:
    Urssaf.fr: https://www.urssaf.fr/portail/home/taux-et-baremes/plafonds.html
    arrêté 2021: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000042748904
  note: Le plafond de la Sécurité sociale n'a pas été revalorisé en 2021 par rapport à 2020.

plafond horaire sécurité sociale:
  acronyme: PHSS
  formule:
    valeur: plafond sécurité sociale temps plein / 1607 heures/an
    arrondi: oui
  unité: €/heure
  références:
    Article D242-19 du code de la sécurité sociale: https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000033516173&cidTexte=LEGITEXT000006073189

plafond journalier sécurité sociale:
  acronyme: PJSS
  formule:
    valeur: plafond sécurité sociale temps plein / 218 jours/an
    arrondi: oui
  unité: €/jour
  références:
    Article D242-17 du code de la sécurité sociale: https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006073189&idArticle=LEGIARTI000006736124

SMIC horaire:
  formule:
    variations:
      - si: établissement . localisation . département = 'Mayotte'
        alors:
          variations:
            - si: date >= 01/08/2022
              alors: 8.35 €/heure
            - si: date >= 01/05/2022
              alors: 8.19 €/heure
            - si: date >= 01/2022
              alors: 7.98 €/heure
            - si: date >= 01/10/2021
              alors: 7.91 €/heure
            - si: date >= 01/2021
              alors: 7.74 €/heure
      - sinon:
          variations:
            - si: date >= 01/08/2022
              alors: 11.07 €/heure
            - si: date >= 01/05/2022
              alors: 10.85 €/heure
            - si: date >= 01/2022
              alors: 10.57 €/heure
            - si: date >= 01/10/2021
              alors: 10.48 €/heure
            - si: date >= 01/2021
              alors: 10.25 €/heure
  note: |
    En principe et sauf « coup de pouce », le SMIC est revalorisé au 1er janvier
    de chaque année. Toutefois une revalorisation doit intervenir en cours
    d'année si l'indice des prix de référence a augmenté de 2% ou plus depuis la
    dernière revalorisation du SMIC.
  références:
    décret: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000046113517
    service-public.fr: https://www.service-public.fr/particuliers/vosdroits/F2300

SMIC temps plein:
  unité: €/mois
  formule:
    produit:
      assiette: durée légale du travail . mensuelle
      facteur: SMIC horaire
  références:
    décret: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000042677359?r=s75zUOEVpR

SMIC temps plein . net imposable:
  titre: SMIC net imposable
  description: Montant du SMIC net imposable pour un temps plein.
  formule:
    recalcul:
      règle: salarié . rémunération . net imposable . base
      avec:
        salarié . contrat . salaire brut: SMIC temps plein
  références:
    barème PAS: https://bofip.impots.gouv.fr/bofip/11255-PGP.html

durée légale du travail:
  valeur: 35 heures/semaine
  avec:
    mensuelle: durée légale du travail * période . semaines par mois
  références:
    Code du travail numérique: https://code.travail.gouv.fr/fiche-ministere-travail/la-duree-legale-du-travail
