// Caisses de retraite
export { default as CIPAV } from '@/assets/images/logos-caisses-retraite/cipav.png'
export { default as CARPIMKO } from '@/assets/images/logos-caisses-retraite/carpimko.png'
export { default as CARMF } from '@/assets/images/logos-caisses-retraite/carmf.png'
export { default as CARCDSF } from '@/assets/images/logos-caisses-retraite/carcdsf.png'
export { default as CNBF } from '@/assets/images/logos-caisses-retraite/cnbf.png'
export { default as CAVEC } from '@/assets/images/logos-caisses-retraite/cavec.jpg'
export { default as IRCEC } from '@/assets/images/logos-caisses-retraite/ircec.jpg'
export { default as CAVP } from '@/assets/images/logos-caisses-retraite/cavp.svg'

// Références (documentation)
export { default as AGIRC_ARRCO } from '@/assets/images/references-images/agirc-arrco.jpg'
export { default as AMELI } from '@/assets/images/references-images/ameli.svg'
export { default as ASSURANCE_RETRAITE } from '@/assets/images/references-images/lassuranceretraite.svg'
export { default as BOFIP } from '@/assets/images/references-images/bofip.impots.gouv.jpg'
export { default as BOSS } from '@/assets/images/references-images/boss.svg'
export { default as BPI } from '@/assets/images/references-images/bpifrance-creation.svg'
export { default as CPSTI } from '@/assets/images/references-images/cpsti.svg'
export { default as ECONOMIE_GOUV } from '@/assets/images/references-images/economie.gouv.png'
export { default as ENTREPRENDRE_SERVICE_PUBLIC } from '@/assets/images/references-images/entreprendre.service-public.jpg'
export { default as FRANCE_TRAVAIL } from '@/assets/images/references-images/france-travail.svg'
export { default as IMPOTS_GOUV } from '@/assets/images/references-images/impots.gouv.svg'
export { default as LEGIFRANCE } from '@/assets/images/references-images/legifrance.svg'
export { default as SERVICE_PUBLIC } from '@/assets/images/references-images/service-public.svg'
export { default as URSSAF } from '@/assets/images/references-images/urssaf.svg'

export { default as CODE_DU_TRAVAIL_NUMERIQUE } from '@/assets/images/references-images/code-du-travail-numerique.svg'
