name: Déploiement en Production
on:
  workflow_run:
    workflows: ['Tests sur Master']
    types: [completed]

permissions:
  contents: read
  statuses: write
  deployments: write

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/_build-and-deploy-prod.yaml
    secrets: inherit
