name: Publish
on:
  workflow_run:
    workflows: ['Tests']
    types: [completed]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package: ['modele-social', 'exoneration-covid']
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: ./.github/actions/install
      - run: yarn workspace ${{ matrix.package }} run build
        env:
          NODE_ENV: production
      - uses: JS-DevTools/npm-publish@0fd2f4369c5d6bcfcde6091a7c527d810b9b5c3f # v4.1.5
        with:
          dry-run: ${{ github.event.workflow_run.head_branch != 'master' }}
          package: ./${{ matrix.package }}/package.json
