name: Règles (non-regression)
on:
  pull_request:
    paths:
      - modele-social/règles/**
      - publicodes/core/**
      - mon-entreprise/test/regressions/**
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-v2
      - run: yarn install --frozen-lockfile
      - run: yarn test:regressions
